import ABOUTUS from './ABOUTUS'
import HOME from './HOME'
import CAREEROPPORTUNITY from './CAREEROPPORTUNITY'
import CONTACTUS from './CONTACTUS'
import ITPROJECTDEVELOPMENT from './ITPROJECTDEVELOPMENT'
import SIGNUP from './SIGNUP'
import EMPLOYER from './EMPLOYER'
import ITTECHNICALSUPPORT from './ITTECHNICALSUPPORT'

export {
    ABOUTUS, HOME, CAREEROPPORTUNITY, EMPLOYER, CONTACTUS, ITPROJECTDEVELOPMENT, SIGNUP,ITTECHNICALSUPPORT
}