import ABOUTUS from './ABOUTUS'
import CAREEROPPORTUNITY from './CAREEROPPORTUNITY'
import CONTACTUS from './CONTACTUS'
import ITPROJECTDEVELOPMENT from './ITPROJECTDEVELOPMENT'
import SIGNUP from './SIGNUP'
import EMPLOYER from './EMPLOYER'

export {
    ABOUTUS, CAREEROPPORTUNITY, EMPLOYER, CONTACTUS, ITPROJECTDEVELOPMENT, SIGNUP
}